apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "http-echo.labels" . | nindent 4 }}
  name: {{ (list (include "http-echo.fullname" .) "instance1") | join "-" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ (list (include "http-echo.fullname" .) "instance1") | join "-" }}
  template:
    metadata:
      labels:
        app: {{ (list (include "http-echo.fullname" .) "instance1") | join "-" }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        name: {{ .Chart.Name }}
        args: ['-text={{ .Values.image.args.text }}', '-listen=:{{ .Values.image.args.listen.instance1 }}']
        ports:
        - containerPort: {{ .Values.containerPort.instance1 | default .Values.image.args.listen.instance1 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe.instance1 | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe.instance1 | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
