name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
    - name: test
      run: dotnet test ./PlayStudios.MyService/
    - name: pack
      run: dotnet publish ./PlayStudios.MyService/PlayStudios.MyService.WebApi/ -c Release -o ./dist
    - name: dockerize
      run: |
        docker build . --file Dockerfile --tag playstudio:$(date +%s)
        docker run --rm playstudio
        
  create-cluster:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.3.0
